### ISSUE TITLE
Setup Terraform plan/apply workflow

### ISSUE THREAD

**Issue by patheard** [cds-snc/url-shortener#46]
## Summary
Create the GitHub plan and apply workflows that will be used to managed our Staging and Production infrastructure.

## Todo
- [ ] Setup OIDC TF plan/apply roles in the AWS accounts
- [ ] PR opened against `main` with `*.tf` changes runs TF plan against Staging
- [ ] PR merged to `main` runs TF apply against Staging
- [ ] PR opened against `main` with version change to infrastructure manifest file runs TF plan against Production
- [ ] PR merged to `main` with infrastructure manifest change runs TF apply against Production
